[plugin]
repository = "https://codeberg.org/Linneris/dalamud-roleplay-profiles.git"
commit = "a506120a8889f9ff93800a7093dd480c62d8404a"
owners = ["Maia-Everett"]
project_path = "RoleplayProfiles"
changelog = """
Update to Dalamud API 15.
"""
