[plugin]
repository = "https://github.com/hunter2actual/DalamudMinesweeper.git"
commit = "33c2c9c4eb63070ab9d2842c44ab86ea111fb650"
owners = ["hunter2actual"]
project_path = "DalamudMinesweeper"
changelog = "Update for FFXIV 7.5 (Dalamud API 15)"
