[plugin]
repository = "https://github.com/yfthbr/musical-guide.git"
commit = "cb7790631725047ba8d78b902266d8e4953f461b"
owners = ["yfthbr"]
project_path = "MusicalGuide"
changelog = """
Added chat commands:
- `/mguide help` to show available commands
- `/mguide gpose` to toggle first person tracking in gpose
- `/mguide toggle` to toggle the plugin on and off
- `/mguide 1pp` to toggle real first person mode
"""
