[plugin]
repository = "https://github.com/powellad/Toastingway.git"
commit = "7ae2d1c978bb1321832732083a380099e9b4fd5b"
owners = ["powellad"]
project_path = "ToastingwayPlugin"
version = "1.3.0.3"
changelog = """
Update to Dalamud API 15.
"""
