[plugin]
repository = "https://github.com/spide-r/WhoDidThat.git"
commit = "b1e2fc1115916282737f7a3108ec015c8176e344"
owners = ["spide-r"]
project_path = "WhoDidThat"
changelog = "Fix minor issue that would cause errors in the plugin log."
