[plugin]
repository = "https://github.com/ArcaneAj/WachuMakeyMaking.git"
commit = "9af09d3c6f49c27c2bd1ef2340eb4c6074b93bb7"
owners = ["ArcaneAj"]
project_path = "WachuMakeyMaking"
changelog = """
 - Fixed bug in filter resource candidates using the incorrect ids
 - Fixed issue where the "Other" tag was overly inclusive of any items that had at least one division that didn't match, rather than all divisions not matching which is intended.
 - Renamed and regrouped headers for clarity
"""
