[plugin]
repository = "https://github.com/ArcaneAj/WachuMakeyMaking.git"
commit = "7390bcce456113e1aa6bf669b52b37dcb961f2d3"
owners = ["ArcaneAj"]
project_path = "WachuMakeyMaking"
changelog = """
 - Added the option to add all the resources needed to craft an item in one go (only direct ingredients, not recursive)
 - Added resource addition filters that let you filter the dropdowns by the type of recipes they appear in. Each box ticked will add more options.
   - e.g. selecting "11-15", "51-55", and "Tabletop" will combine all things that can be crafted from those 3 groups and find the ingredients referenced by all of them.
   - The 4 "Other" divisions that start with "Only" are mutually exclusive pairs that restrict, rather than add, from the combined list you selected above.
"""
