[plugin]
repository = "https://github.com/ArcaneAj/WachuMakeyMaking.git"
commit = "ca9a9603d63fd5fbbeace426d089c8caffa10c97"
owners = ["ArcaneAj"]
project_path = "WachuMakeyMaking"
changelog = """
 - Fixed bug in filter resource candidates using the incorrect ids
"""
