[plugin]
repository = "https://github.com/Sohtoren/Altoholic.git"
commit = "6701e877832cbe51890f8798bca8bf87cd5b1c59"
owners = ["Sohtoren"]
project_path = "Altoholic"
changelog = """\
- **Progress**:
    - Event: Add Blunderville 2026
	- Blunderville: Add outfit and furnitures to rewards in Blunderville tab
"""
