[plugin]
repository = "https://github.com/Sohtoren/Altoholic.git"
commit = "ba682abcd4f227b07aa5cbba9c3acfd463019b7c8"
owners = ["Sohtoren"]
project_path = "Altoholic"
changelog = """\
- **Currencies**: Fix search following currencies rework
"""
