[plugin]
repository = "https://github.com/Sohtoren/Altoholic.git"
commit = "5c8d3ee9902cc5f0b67692107821e83bd7177d7b"
owners = ["Sohtoren"]
project_path = "Altoholic"
changelog = """\
- **General**: Update dependencies
"""
