[plugin]
repository = "https://github.com/elchupi/AnimSwapper.git"
commit = "f02e554c34a026874de88b8f082a20a4e92554cc"
owners = ["elchupi"]
project_path = "AnimSwapper"
changelog = "Initial release."
