[plugin]
repository = "https://github.com/elchupi/AnimSwapper.git"
commit = "8aa495ee70ce23debcbb2fe56573d28a335f5b47"
owners = ["elchupi"]
project_path = "AnimSwapper"
changelog = "Initial release."
