[plugin]
repository = "https://github.com/elchupi/AnimSwapper.git"
commit = "05f0ed89bf4bb85edfb515f20f8a387bfdae532a"
owners = ["elchupi"]
project_path = "AnimSwapper"
changelog = "Initial release."
