[plugin]
repository = "https://github.com/NeNeppie/AvantGarde.git"
commit = "8f560a9701f249ed29675b85d374fd7f37421d8e"
owners = ["NeNeppie"]
project_path = "AvantGarde"
changelog = """
**Available for testing:**
- Automatic Crowdsourcing
 - Submissions are uploaded to Xivstats' database. Special thanks to Infi.
 - Collects items & dyes used, weekly theme information and score.
 - Private or sensitive data is never collected.
 - Requires Opt-in (Plugin functionality is unaffected by your choice).
 - See how many times a particular piece was used among the userbase.
- Onboarding window that explains everything
- We're so back
"""
