[plugin]
repository = "https://github.com/Caraxi/ItemSearchPlugin.git"
commit = "f7aed15d97b0d1e7d602e1a74275679a875bc29c"
owners = [
    "Caraxi", "MKhayle",
]
project_path = "ItemSearchPlugin"
changelog = """
-# API 15 update
-# 7.5 item data update
"""