[plugin]
repository = "https://github.com/Caraxi/ItemSearchPlugin.git"
commit = "6c1a96cbe391518b4d205039b41ba40dd5114e47"
owners = [
    "Caraxi", "MKhayle",
]
project_path = "ItemSearchPlugin"
changelog = """
-# 7.55 item data update
-# Fixture preview fix (thanks Caraxi!)
"""