[plugin]
repository = "https://github.com/Critical-Impact/AllaganTetris.git"
commit = "57e2bfdc0d2d61619718ed5ffc3dd9967f0c9989"
owners = [ "Critical-Impact",]
project_path = "AllaganTetris"
version = "1.3.0.0"
changelog = "### Changed\n- API15 update"
