[plugin]
repository = "https://github.com/smileyhead/conditional-focustarget.git"
commit = "8b5f771d52c9f4c4633aea65b5e9f352e34d5970"
owners = ["smileyhead"]
project_path = "StickyFocusTarget"
changelog = """
Bump Dalamud API to 15.0.0"""