[plugin]
repository = "https://github.com/Bluefissure/NoKillPlugin.git"
commit = "a00aed34c38ce2eca87170eb83ca81e9b69e17df"
owners = ["Bluefissure"]
project_path = "NoKillPlugin"
changelog = """API15"""
