[plugin]
repository = "https://github.com/radax864/CWLSLastSeenTool.git"
commit = "ac56998775797d6573ea324d44f5c8f1ff388bd9"
owners = ["radax864"]
project_path = "CWLSLastSeenTool"
changelog = """
Version 2.0.0.0

- CWLSLastSeenTool has been renamed to Linkshell Tools
- The /cwlslst command has been renamed to /shelltools
- Data recorded has been standardised between Cross-world and Home World Linkshells
- A lot of the plugin has been rewritten to be easier to maintain and extend going forward
- Cross-world Linkshells now properly support multiple data centers by recording the data center alongside the Cross-world Linkshell name
- Fixed CSV corruption when Linkshell names contained commas (data is now stored as tab separated)
"""
