[plugin]
repository = "https://github.com/tenyu27/PartySortPlus.git"
commit = "b07e15acaf46747a779686fab5522f9a505764bd"
owners = ["Rietty","tenyu27"]
project_path = "PartySortPlus"
changelog = "Update to support 7.4 changes."
