[plugin]
repository = "https://github.com/nebel/xivPartyIcons.git"
commit = "15cfdb124865f316d63d0482146c01a5412beefa"
owners = [
    "shdwp",
    "avafloww",
    "abashby",
    "nebel"
]
project_path = "PartyIcons"
