[plugin]
repository = "https://github.com/nebel/xivPartyIcons.git"
commit = "bb0f06243c7e8ae28242b7a53a08f202ee6db292"
owners = [
    "shdwp",
    "avafloww",
    "abashby",
    "nebel"
]
project_path = "PartyIcons"
