[plugin]
repository = "https://github.com/sleeds2/jobroulette.git"
commit = "062d216ec6d5e40fe9047cb0e89fe13aca2276ff"
owners = ["sleeds2"]
maintainers = ["mchudoba"]
project_path = "JobRoulettePlugin"
changelog = """\
**Update**: Added /jr as an alias for /jobroulette.
"""
