[plugin]
repository = "https://github.com/MythicPalette/Wordsmith-DalamudPlugin.git"
commit = "6145c1ef068d0c200403992ab09c4c06ee3d8e4a"
owners = [
    "MythicPalette"
]
project_path="Wordsmith"
changelog = """# Wordsmith v1.16.1 Patch Notes
* Updated to the latest Dalamud api.
"""
