[plugin]
repository = "https://github.com/MythicPalette/Wordsmith-DalamudPlugin.git"
commit = "64360ffff856dd1f7d4e30efc335b534eb0fe99b"
owners = [
    "MythicPalette"
]
project_path="Wordsmith"
changelog = """# Wordsmith v1.16.1 Patch Notes
* Updated to the latest Dalamud api.
"""
