[plugin]
repository = "https://github.com/Helios747/AdaptiveHudPlugin.git"
commit = "a411d7815f565bd98d66706fbc4534e5e1de4866"
owners = [
    "Helios747"
]
project_path = "AdaptiveHud"
changelog = "API 15"
