[plugin]
repository = "https://github.com/Helios747/AdaptiveHudPlugin.git"
commit = "3082e151cb4d1c02a0ea94343d74669facde9530"
owners = [
    "Helios747"
]
project_path = "AdaptiveHud"
changelog = "API 15"
