[plugin]
repository = "https://github.com/fitzchivalrik/compass.git"
commit = "27b670426d534f6eec70178475653c48f763d570"
owners = ["fitzchivalrik"]
project_path = "Compass"
changelog = """
- chore: Update to API15 (thanks @ashen-dawn)

NOTE: Since 7.0, Compass seems to work funky in some cases.
I am sorry, but I cannot promise that I will manage to work on plugins for the foreseeable future.
I can, however, promise to have a look at any potential PR in a timely manner.
"""
