[plugin]
repository = "https://github.com/BalthierArt/EchoChat.git"
commit = "85b36b5fc60b62aac611d29d2c7d573ec30d14a5"
owners = ["BalthierArt"]
project_path = "."
changelog = "Updated Chat Echo for Dalamud API 15 and added optional game log effect channels."
