[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "b72fbfeb77a4a6eeb0b4aabc275a18f89f49ddf2"
owners = ["seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.3.2
- API 15 update
"""