[plugin]
repository = "https://github.com/meoiswa/ClarityInChaos.git"
commit = "0b66ff8098ed5f80b13296ed8294e8cab6a07693"
owners = ["meoiswa"]
project_path = "ClarityInChaos"
changelog = """
Version 2.5.1.0:
 - Updated to API15
"""
