[plugin]
repository = "https://github.com/wompscode/NowPlaying.git"
commit = "c2ebe6014b95015cedf9b0956ac663f077ee9abf"
owners = ["wompscode"]
project_path = "NowPlaying"
changelog = "now with Linux support: thanks beerpsi."