[plugin]
repository = 'https://github.com/RokasKil/EmoteLog.git'
commit = '4352901e6b647f265814c4a03e67af105de11f46'
owners = [ 'RokasKil' ]
project_path = 'EmoteLog'
changelog = """
- 7.5 and API15 update
"""

