[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "1447b82281679e700ac8d946baac4bcef4326c38"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Updated to 7.5 - Zero has been added!"
