[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "313533cdae9f104634dfe59c1416bd27a0728fb4"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Big UI Changes, bugfixes, etc."