[plugin]
repository = "https://github.com/MapleHinata/Dalamud.FullscreenCutscenes.git"
commit = "816e2b434241d510f81a93b58f94f8f7c20044fc"
owners = [
    "MapleHinata",
]
project_path = "Dalamud.FullscreenCutscenes"
