[plugin]
repository = "https://github.com/devckuw/BetterFriendList.git"
commit = "4d8c9eae150a89192632090b16e3cf042d7eeecc"
owners = ["devckuw"]
project_path = "BetterFriendList"
changelog = """
v2.1.4.2:
- add beastmaster icon
"""
