[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "6a41969838a82035d6838ae18e6cd8133d15097a"
owners = ["Glyceri"]
	changelog = """
[2.9.0.1] 
Fixed an issue where the party list wouldn't show the petname properly.
"""















