[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "8f0b9c2c2656c6b74c959f5984a4a54f26b9baeb"
owners = ["Glyceri"]
	changelog = """
[3.0.0.2] 
- Fixes an issue where switching alt's wouldn't push an update over IPC.
"""















