[plugin]
repository = 'https://github.com/caitlyn-gg/Glamaholic.git'
commit = '23e4f4802cb49cf53c888287ea7c68d9d7e57a93'
owners = [ 'caitlyn-gg' ]
changelog = """
- Updated for API 15

For troubleshooting, please enable Troubleshooting mode (Settings -> Troubleshooting mode), reproduce the issue, then post any log line from `/xllog` starting with `[Troubleshooting]`. Thanks!
"""
