[plugin]
repository = "https://github.com/kk-triplesix/QuestieBestie.git"
commit = "68fcead3aaebef0e17cb3f5007c594c04eb897db"
owners = [ "kk-triplesix" ]
changelog = "Replace ExtractText with ToString, remove unnecessary null checks on GetExcelSheet, replace manual PushStyleVar/Pop with ImRaii.PushStyle"
