[plugin]
repository = "https://github.com/karashiiro/TextToTalk.git"
commit = "6f372c354644f3b72c946992d1537d4217fab5a3"
project_path = "src/TextToTalk"
owners = ["karashiiro"]
changelog = """\
- **General**: Fixed UI error on channel selection tab.
- **System**: Fixed TTS delays.
"""
