[plugin]
repository = "https://github.com/karashiiro/TextToTalk.git"
commit = "51c3958486d4ef44029318c21bfd5bc78cec0ffc"
project_path = "src/TextToTalk"
owners = ["karashiiro"]
changelog = """\
- **System**: Fixed random stops during TTS playback, especially with NaturalVoiceSAPIAdapter
"""
