[plugin]
repository = "https://github.com/karashiiro/TextToTalk.git"
commit = "e5cf5404b388a3223b346853073536e59822dbb7"
project_path = "src/TextToTalk"
owners = ["karashiiro"]
changelog = """\
- **Megaphone**: Added [Megaphone](<https://github.com/barrcodes/xiv-megaphone>) TTS backend.
- **General**: Adjusted default (fresh install) settings for quicker new-user onboarding.

Thanks to `@barrcodes` for the improvements in this update!
"""
