[plugin]
repository = "https://github.com/Critical-Impact/AllaganMarket.git"
commit = "2242b07cec028ffa3454bfc7b255d85ce9cb5b7e"
owners = [ "Critical-Impact",]
project_path = "AllaganMarket"
version = "1.4.0.2"
changelog = "### Changed\n- Update sig for 7.55"
