[plugin]
repository = "https://github.com/Critical-Impact/AllaganMarket.git"
commit = "33e4510f6577f3945f2f4f84674e2ca284453de0"
owners = [ "Critical-Impact",]
project_path = "AllaganMarket"
version = "1.4.0.0"
changelog = "### Changed\n- API15 update"
