[plugin]
repository = "https://github.com/Critical-Impact/AllaganMarket.git"
commit = "ae150f9366e3c42173362c566f7817c8de56fbd7"
owners = [ "Critical-Impact",]
project_path = "AllaganMarket"
version = "1.4.0.2"
changelog = "### Changed\n- Update sig for 7.55"
