[plugin]
repository = "https://github.com/NeNeppie/AvantGarde.git"
commit = "e849811662279877608c0b274aa14399217b9692"
owners = ["NeNeppie"]
project_path = "AvantGarde"
changelog = """
Update for Patch 7.5 / API 15
"""

