[plugin]
repository = "https://github.com/NeNeppie/AvantGarde.git"
commit = "96b47c03570fe04e72e0f453a0e771959c228eb4"
owners = ["NeNeppie"]
project_path = "AvantGarde"
changelog = """
- Prevent duplicate submissions if Tracky is also installed.
"""

