[plugin]
repository = "https://github.com/ItsBexy/CrossUp.git"
commit = "89ef4b2b9b304090e807ad114624dba2ea949b4e"
owners = [
    "ItsBexy",
]
changelog = """
- Updated for 7.5 / api 15
"""



