[plugin]
repository = "https://github.com/ItsBexy/CrossUp.git"
commit = "44b1d6b0b63d5edb3de32b7817f94cd887e03ecd"
owners = [
    "ItsBexy",
]
changelog = """
- Updated for 7.5 / api 15
"""



