[plugin]
repository = "https://github.com/Noevain/VoiceDirector.git"
commit = "6bddd11459511dda7da8ea38f066a4611f974744"
owners = ["Noevain"]
project_path = "VoiceDirector"
changelog = "API15 updated,yipee"
