[plugin]
repository = "https://github.com/Saevath/CrystalRadio.git"
commit = "2711f239c599ea25660e74e0af1850c507715a15"
owners = [ "Saevath" ]
changelog = """
- Added support for custom stations
- Fixed plugin volume disabling game volume
- Added volume gain control and equalizer
- Bugfixing
- Updated API Level
"""
