[plugin]
repository = "https://github.com/Saevath/CrystalRadio.git"
commit = "b152403f005eb818c362addbed8eb6f816d4b8dc"
owners = [ "Saevath" ]
changelog = """
- Added support for custom stations
- Fixed plugin volume disabling game volume
- Added volume gain control and equalizer
- Bugfixing
- Updated API Level
"""
