[plugin]
repository = "https://github.com/mashirochan/FFXIV-GraceGawker.git"
commit = "1f08eb40ccdbddca736e39002d2f1b19bd36cd7e"
owners = ["mashirochan"]
project_path = "GraceGawker"
changelog = "Update to API 15"
