[plugin]
repository = "https://github.com/devckuw/DiscordBotFFXIV.git"
commit = "1a34a36d24100b9a265faa13bd9672d1e2624b14"
owners = ["devckuw"]
project_path = "DiscordBotFFXIV"
changelog = """
- first release
"""
