[plugin]
repository = "https://github.com/Haplo064/PixelPerfect.git"
commit = "162c07cf7bc493bfe4be140e3b3f16920bd7e81c"
owners = ["Haplo064"]

changelog = "7.5ish. Added Nuclear launch codes."
