[plugin]
repository = "https://github.com/RedMage1993/MimicryHelper.git"
commit = "9bfebe7a13988deefef587cbdbe7757273eff31c"
owners = ["RedMage1993"]
project_path = "MimicryHelper"
changelog = "Rebuilt for patch 7.5"