[plugin]
repository = "https://github.com/Valiice/SpotifyHonorific.git"
commit = "411ce625d1ed5419890279261fefa3bb050f5989"
owners = ["Valiice"]
project_path = "SpotifyHonorific"
changelog = "Displays your currently playing Spotify track as your FFXIV honorific title.\nInitial Release"
