[plugin]
repository = "https://github.com/kissorjeyabalan/dalamud-chatcoordinates.git"
commit = "109faec1ad45de61a1873c42cfb5da802f333f92"
owners = [
    "kissorjeyabalan",
]
project_path = "ChatCoordinates"
changelog = "API 15"
