[plugin]
repository = "https://github.com/AlexCSDev/XIVWindowResizer.git"
commit = "a6a16d3405e3c09c31f0fce0202300f999f0c8f2"
owners = ["AlexCSDev"]
project_path = "XIVWindowResizer"
changelog = "Updated for 7.5"
