[plugin]
repository = "https://github.com/Tischel/TPie.git"
commit = "572e3dbf7d4fb21430e78c24683e3b4d89b77e6f"
owners = ["Tischel"]
project_path = "TPie"
changelog = "- Fixing plugin errors with Beastmaster."
