[plugin]
repository = "https://github.com/ktisis-tools/ffxiv-pathfinder.git"
commit = "3b417ffe3060899ee4aef9d52e00e6682b89697c"
owners = ["chirpxiv", "sleepybnuuy"]
project_path = "Pathfinder"
changelog = "DAPI 15"
