[plugin]
repository = "https://github.com/ktisis-tools/ffxiv-pathfinder.git"
commit = "138a32c9cf1b0d9585bbef25f274eea4781503c9"
owners = ["chirpxiv", "sleepybnuuy"]
project_path = "Pathfinder"
changelog = "DAPI 15"
