[plugin]
repository = "https://github.com/Critical-Impact/AutoMountBGM.git"
owners = [ "Critical-Impact",]
project_path = ""
commit = "01a64d0c4806fc9f761670bfd304f14ab17e2a74"
changelog = "### Fixed\n- Support for 7.5"
version = "4.0.0"
