[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "d4a7fa2f47a756d625cccaddf23a9b2862279a34"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
API 15 + 7.5 changes
"""
