[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "eb586bae3d60d574cb41097723e7c594071e745d"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
Add basic IPC service, by Zeffuro
"""
