[plugin]
repository = "https://github.com/RajahOmen/BisBuddy.git"
commit = "6b43e64ac05533048c0583c4db01b9a8f2f93ac0"
owners = ["RajahOmen"]
project_path = "BisBuddy"
changelog = """\
UI bugfixes / assert fixes
"""
