[plugin]
repository = "https://github.com/Aida-Enna/Doorbell.git"
commit = "4ca64ffa6ffe37115740700ba79ddd4cc97ff004"
owners = ["Aida-Enna"]
project_path = ""
changelog = "- Updated for 7.5\n- Added support for the new Minimalist Dark housing"
