[plugin]
repository = "https://github.com/apetih/rtyping.git"
commit = "2cf0ae5957b3da07c489625ca3d266b36e832c43"
owners = ["apetih"]
project_path = "client/rtyping"
changelog = """
- Added ChatTwo typing state integration via IPC (thanks ZeroTheScyther)
"""