[plugin]
repository = "https://github.com/Kurochi51/TickTracker.git"
commit = "625ba8e86612703a1694d38d4f96065d70e40db9"
owners = ["Kurochi51"]
project_path = "TickTracker"
changelog = """
- Quarterly API Bump
"""
