[plugin]
repository = "https://github.com/grittyfrog/MacroMate.git"
commit = "ffb573944d064ddbf3e795cd423a88c970846943"
owners = ["grittyfrog"]
project_path = "MacroMate"
version = "1.0.27.3"
changelog = """
- Add Gearset link condition
- Fix "Run Selected" printing C# types instead of selected text
"""
