[plugin]
repository = "https://github.com/grittyfrog/MacroMate.git"
commit = "c865873388f0dbf36a406685b01eef3b8bf4e61f"
owners = ["grittyfrog"]
project_path = "MacroMate"
version = "1.0.27.2"
changelog = """
- Fix issue loading config containing certain conditions (i.e. Target == Pc)
"""
