[plugin]
repository = "https://github.com/grittyfrog/MacroMate.git"
commit = "4b41fc0b40c6156fe67b0a3f64d83a4f00e430ae"
owners = ["grittyfrog"]
project_path = "MacroMate"
version = "1.0.27.4"
changelog = """
- Fix constantly writing HOTBAR.dat 
"""
