[plugin]
repository = "https://github.com/Pistachio-dev/FlashOnReadyCheck.git"
commit = "9a98e75f7abac7096bf15d0377de03cfa26265e0"
owners = ["Pistachio-dev"]
project_path = "FlashOnReadyCheck"
changelog = "Patch 7.5"
