[plugin]
repository = "https://github.com/KhloeLeclair/WTSync.git"
commit = "5071f4d31c89b439347cd384ab1073ce31c583b8"
owners = [ 
	"KhloeLeclair"
]
maintainers = [
	"BoxuChan"
]
project_path = ""
changelog = """
Updated for FFXIV 7.5 and Dalamud API 15.
"""