[plugin]
repository = "https://github.com/caitlyn-gg/InventorySearchBar.git"
commit = "d87cf89a9b54792b9035ba8c01704137b39a2728"
owners = ["caitlyn-gg"]
project_path = "InventorySearchBar"
changelog = "- Updated dependencies (fixes Retainer search again)"
