[plugin]
repository = "https://github.com/caitlyn-gg/InventorySearchBar.git"
commit = "88b8bf5764a72d8c579c67846724db870237a0a7"
owners = ["caitlyn-gg"]
project_path = "InventorySearchBar"
changelog = "- Speculative fix for a rare crash when exiting the game"
