[plugin]
repository = "https://github.com/caitlyn-gg/InventorySearchBar.git"
commit = "55ea35005257afb4ffeea27dca45a8b5b4def13f"
owners = ["caitlyn-gg"]
project_path = "InventorySearchBar"
changelog = "- Added tradable filter"
