[plugin]
repository = 'https://git.sharlayan.cloud/anna/OrangeGuidanceTomestone.git'
commit = '2b71fe660b16e05fdc0f8a8ff0222390652fae93'
owners = [ 'anna-is-cute' ]
project_path = 'client'
changelog = """\
- Update to new backend API
- Fix issue when writing new sign
- Handle viera ear toggle
"""
