[plugin]
repository = "https://github.com/xorelcodes/QuietTheDen.git"
commit = "8327784f2a25cf1c01af4040c6e2e13c11bf7c4f"
owners = ["xorelcodes"]
project_path = "QuietDen"

changelog = "QuietDen v1.2.3"



