[plugin]
repository = "https://github.com/Brolijah/SimpleTriggers.git"
commit = "9f49d0be4eb2e96e7b8420c606abfa3b5abb00dd"
owners = ["Brolijah"]
project_path = "SimpleTriggers"
changelog = """
## SimpleTriggers v1.0.4.3
* Cleaned up preset exporting to remove default values from output string.
* Fixes to category renaming. If renaming *just* a category will check if the name already exists and will merge.
"""
