[plugin]
repository = "https://github.com/zw3lf/ffxiv-coord-importer.git"
commit = "d126a7faaec9978afa652411372c389b4bafd524"
owners = ["zw3lf", "dit-zy"]
project_path = "CoordImporter"
changelog = "Add Ultimahunt support"
