[plugin]
repository = "https://github.com/MarcusBullock22/HotPotatoPlugin.git"
commit = "d1ffa6c8ee2d81411a6cf05482807f01c600f3ba"
owners = ["MarcusBullock22"]
project_path = "HotPotatoPlugin"
changelog = "Initial testing release of Hot Potato Game Manager."