[plugin]
repository = "https://github.com/seventity7/MaidenAlert.git"
commit = "7ab3cd7c5a26c4dc595fbf9affc4adef63ef7bc7"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Initial Release+detection system improvement"
