[plugin]
repository = "https://github.com/seventity7/MaidenAlert.git"
commit = "4281cbf7c6515bd1a61d368e5653eac0c95f540d"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Update 1.0.0.4 new features added"
