[plugin]
repository = "https://github.com/seventity7/MaidenAlert.git"
commit = "5c800f63e14acc93d46dc32f709865c8b912d5e9"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Initial Release"
