[plugin]
repository = "https://github.com/WesselKuipers/FCNameColor.git"
commit = "a2795c6da72d72bd783b2f10487155bfb5e3939a"
owners = ["WesselKuipers"]
project_path = "FCNameColor"
changelog = """
- Add nameplate hiding feature

Feedback and suggestions on this feature would be appreciated!
"""
