[plugin]
repository = "https://github.com/PunishedPineapple/WhatDidYouSay.git"
commit = "17272701de93be62ebf2564add7f60e947b8d1d8"
owners = [
    "PunishedPineapple",
]
project_path = "WhatDidYouSay"
changelog = '''
- Updated for Dalamud API 15.
'''