[plugin]
repository = "https://github.com/Mary-Usagi/FFXIV-HUDLayoutHelper.git"
commit = "c2edbc6573609756d2fa12faba5aaa19ee70dcdb"
owners = ["Mary-Usagi"]
project_path = "HUDLayoutHelper"
changelog = "Update to API 15"
