[plugin]
repository = 'https://github.com/RokasKil/SteamRecordingEnhanced.git'
commit = 'f4ef14d21cd0b9b6efc62148391415b34704f1d2'
owners = [ 'RokasKil' ]
project_path = 'SteamRecordingEnhanced'
changelog = """
- Fixed a Steam crash
"""
