[plugin]
repository = 'https://github.com/RokasKil/SteamRecordingEnhanced.git'
commit = '84526d7ab542608aed28f3f2ba2cd6a5b1b9637c'
owners = [ 'RokasKil' ]
project_path = 'SteamRecordingEnhanced'
changelog = """
- Fixed Duty wiped and Duty started labels being swapped in the configuration menu
"""
