[plugin]
repository = "https://github.com/OOFGamesss/AethericFlow.git"
commit = "6762439914696607e066a125d46044bb4d6d1611"
owners = ["OOFGamesss"]
project_path = "AethericFlow"
changelog = "- Two new appearance toggles has been added.\n- Show teleport icon only will remove the teleport text and add just the aetheryte crystal as a clickable teleport link.\n- Show clock icon only will remove the walk hint text if enabledand add just the clock icon when walking would be quicker without showing the text."
