[plugin]
repository = "https://github.com/Sohtoren/Altoholic.git"
commit = "91ddb68d1ce64dec30d61ac647668649b71c5a51"
owners = ["Sohtoren"]
project_path = "Altoholic"
changelog = """\
- **Code**: Moving reward drawing and tooltip to own helper file and refacto. Fix some rewards tooltips having multiple characters and weirds icons
"""
