[plugin]
repository = "https://github.com/Sohtoren/Altoholic.git"
commit = "d17728ed1bc0f6dd440cf6ecbbdc35e35e860b8a"
owners = ["Sohtoren"]
project_path = "Altoholic"
changelog = """\
- **General**: Add backup cleanup
- **Timers**: Raids
"""
