[plugin]
repository = "https://github.com/Era-FFXIV/QuestShare.Plugin.git"
owners = ["nathanctech"]
project_path = "QuestShare.Plugin"
commit = "cbc24feacabd4841ea5d5c3437d6b4ef79552dee"
version = "1.2.15.0"
