[plugin]
repository = "https://github.com/Glyceri/AcquisitionDate.git"
commit = "251381060984098e12bd7d17eef810ce6f6e4a23"
owners = ["Glyceri",]
	changelog = """
[1.1.0.2]
Tentative fix for hang on startup.
"""
