# stable/AetherBlackbox/manifest.toml
[plugin]
repository = "https://github.com/rail2025/AetherBlackbox.git"
commit = "f3256bdaee4863d07c8471f2aa1ff046970b52fe" 
owners = ["rail2025"]
# project_path = "AetherBlackbox" # Only uncomment and use if your .csproj is NOT at the root of your repo
changelog = "v7.56.1.1: BST icon support\nv7.56.1.0: overlays bounce back on window resize, map calibration scaling propagates live sync too\nv7.56.0.1:live sync cache fix\nv7.56.0.0: Survival calculator added. See if you would have lived."
