[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "cdd3bac3ddad6f22047ec0928f31595b681c5781"
owners = [
    "Infiziert90"
]
project_path = "EurekaTrackerAutoPopper"
