[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "cd0dcf5da03e5661aa0c78e6e887038964f6de44"
owners = [
    "Infiziert90"
]
project_path = "EurekaTrackerAutoPopper"
