[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "b6c0c3b3698130abdd6b35bf64d77dd1c7821f14"
owners = [
    "Infiziert90"
]
project_path = "EurekaTrackerAutoPopper"
 
