[plugin]
repository = "https://github.com/Nerifyra/RpUtils.git"
commit = "2b526226a9e6f6b7d735e62227bee29852f19357"
owners = ["Nerifyra", "erroch"]
project_path = "RpUtils"
changelog = """
0.5.0 (2026.4.16)
- First pass at lobbies
- First pass at encounters
- First pass at dice rolls
- Adding changelog window and more configuration options

0.4.0 (2026.3.11)
- Major refactor of the plugin
- Adding first pass on roleplay activities to sonar

0.3.2 (2025.12.27)
- Updated for 7.4, migrated to Dalamud SDK

"""

