[plugin]
repository = "https://github.com/NeNeppie/LightsCameraAction.git"
commit = "a68485bd2103955ba437bcf950645c43e05b6579"
owners = ["NeNeppie"]
project_path = "CameraLoader"
changelog = "Update for Patch 7.5 / API 15"

