[plugin]
repository = "https://github.com/Hiroa/LazyGatherer.git"
commit = "d07e1ced7572ab49c83c141dbe99c753ca366882"
owners = ["Hiroa"]
project_path = "LazyGatherer"
changelog = """
Version 1.4.2: 
 - Improve GP alert system
 - Add command for GP alert configuration
"""