[plugin]
repository = 'https://github.com/MKhayle/Globetrotter.git'
commit = '83c5c1f007f93f304e2bfbda904706335d514577'
owners = [ 'anna-is-cute', 'chirpxiv', 'MKhayle' ]
changelog = '-# API 15 update'
