[plugin]
repository = "https://github.com/devckuw/DiscordBotFFXIV.git"
commit = "caaa4d7f873189a695101957d9dfc86a655560e7"
owners = ["devckuw"]
project_path = "DiscordBotFFXIV"
changelog = """
v1.1.2.4:
update help text
"""
