[plugin]
repository = "https://github.com/meoiswa/TotalLevelPlugin.git"
commit = "575bf461ceba13189f70b2b8a0b4dcf78b7ccb97"
owners = ["meoiswa"]
project_path = "TotalLevelPlugin"
changelog = """
Adds a suffix to the Character's Name in the Search Info panel totaling the level of their jobs/classes, similar to Runescape.

Version 0.0.1.1:
 - New Icon by SnoodleWolfieB
 - Updated to API15
"""
