[plugin]
repository = "https://github.com/ImOv3rburdened/LapCatCounter.git"
commit = "1c584bfa3b677c75a2777c4be36572f59d1aa48c"
owners = ["ImOv3rburdened"]
project_path = "LapCatCounter"
changelog = "v1.1.0.0. Updated dalamud API level. Removed fallback code for lap detection that was removed in the latest API. Version bump  and new icon"
