[plugin]
repository = "https://github.com/s5bug/AutoTimer.git"
commit = "82207f1142e67d1fe62f143199af70dd3c212386"
owners = ["s5bug"]
project_path = "AutoTimer"
changelog = '''
- Update to 7.5'''
