[plugin]
repository = "https://github.com/hunter2actual/BigNaelQuotes.git"
commit = "b80f83403b51fde537125a363435931ba5682aa2"
owners = ["hunter2actual"]
project_path = "BigNaelQuotes"
changelog = "Update for api15"
