[plugin]
repository = "https://github.com/LatencyBryer/QuickSymbols.git"
commit = "8fa7288585ded8883778f0ee86503b8e11c9a19a"
owners = ["LatencyBryer"]
maintainers = ["LatencyBryer"]
project_path = "."
changelog = """
### Icon update
- Changed icon with better resolution
- Updating new Username
"""
