[plugin]
repository = "https://github.com/megurte/WhichMount.git"
commit = "a21d37aaa0ef06cecd2cb0ffed5ae6222dbd6665"
owners = [
    "megurte"
]
project_path = "WhichMount"
version = "1.4.2"
changelog = """
Version 1.4.2:
  - 7.5 patch mount data update
"""