[plugin]
repository = "https://github.com/Critical-Impact/InventoryTools.git"
commit = "052739db6b2ff066f1938f3c2e6144ae2e9252dd"
owners = [ "Critical-Impact",]
project_path = "InventoryTools"
version = "1.15.0.10"
changelog = "### Fixed\n- Updated sig for 7.55\n### Changed\n- Lumina Supplemental data update for 7.55"
