[plugin]
repository = "https://github.com/Critical-Impact/InventoryTools.git"
commit = "057c10316395899a5ebdc2d4fd3129fe3f994370"
owners = [ "Critical-Impact",]
project_path = "InventoryTools"
version = "1.15.0.1"
changelog = "### Fixed\n- Fix an issue that occurs when trying to open the \"Open Map\" menu for certain spearfishing items."
