[plugin]
repository = "https://github.com/NotNite/MoonbaseOmega.git"
commit = "e35314fee8af6418e2599a94d747c75e5e585ac0"
owners = ["NotNite"]
maintainers = ["GayPotatoEmma"]
project_path = "MoonbaseOmega"
