[plugin]
repository = "https://github.com/NadyaNayme/TidyChat.git"
commit = "b1375d71cf366cfd8bff351fdeb0665f90651cb3"
owners = ["Kagekazu"]
maintainers = ["NadyaNayme"]
project_path = "TidyChat"
