[plugin]
repository = "https://github.com/Elypha/SimpleMarketBoard.git"
commit = "ff1694c987327142bc6ed80ffd92a3248e13f7cc"
owners = ["Elypha"]
project_path = "SimpleMarketBoard"
changelog = """
v1.12.0.0
- Fix a compatibility issue with Universalis.
"""
