[plugin]
repository = "https://github.com/MapleRecall/AcrylicXIV.git"
commit = "883a77e5376e04766c28fcd9d952ae7473429ca4"
owners = ["MapleRecall"]
project_path = ""
changelog = "Initial testing release."