[plugin]
repository = "https://codeberg.org/keysmashes/WhosTalking.git"
commit = "65e13c87edcd76ba880b756f2ac46e295a1652b9" # version 0.8.10.0
owners = ["keysmashes"]
project_path = "WhosTalking"
changelog = """\
Updated for API 15 (patch 7.5).
"""
