[plugin]
repository = "https://github.com/Abyeon/Housingway.git"
commit = "cf2bebbef6eeef8fa6e03284f69ab39b1b346252"
owners = ["Abyeon"]
maintainers = ["Abyeon"]
project_path = "Housingway"
changelog = "Initial Release"
