[plugin]
repository = "https://github.com/Abyeon/Housingway.git"
commit = "361c235033b8a43b61fc07b71cad3a6431da322d"
owners = ["Abyeon"]
maintainers = ["Abyeon"]
project_path = "Housingway"
changelog = "Initial Release"
