[plugin]
repository = "https://github.com/Abyeon/Housingway.git"
commit = "c849aa1e02c4cdfebc353b3aa6125cc49e289bc8"
owners = ["Abyeon"]
maintainers = ["Abyeon"]
project_path = "Housingway"
changelog = "Initial Release"
