[plugin]
repository = "https://github.com/Ibcrootbeer/RetainerAlerts.git"
commit = "9b84036fe28bd21c458201d54fc59cc57862740b"
owners = ["Ibcrootbeer"]
project_path = "RetainerAlerts"
changelog = "Alert window will not show unless on home world now."
