[plugin]
repository = "https://github.com/HybridEidolon/eid-ffxiv-plugins.git"
commit = "a2fe8b568beefd6e02491416f64755f8278042e7"
owners = ["HybridEidolon"]
project_path = "DynamicUIScaling"
changelog = """\
Updated to API 15.
"""
