[plugin]
repository = "https://github.com/Drahsid/BetterShadows.git"
commit = "1ae5e9d3a712ab08d5b6af979b863fc1a0835da9"
owners = ["Drahsid"]
project_path = "BetterShadows"
changelog = """
- API15
"""

