[plugin]
repository = "https://github.com/danielbrenom/MacroRecorded.git"
commit = "3ec72502d157335f446f3e79047d2062d3d5c9cb"
owners = [
    "danielbrenom",
]
project_path = "MacroRecorded"
changelog = """- Updated API 15
 """
