[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "deb285920424b9584c0eac782e688a7b533d4902"
owners = [
    "Bronya-Rand",
    "vmfunc"
]
maintainers = [
    "Bronya-Rand",
    "vmfunc",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
