[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "f336a74e18c52e8a8cd225f1b7417db719862a78"
owners = [
    "Bronya-Rand"
]
maintainers = [
    "Bronya-Rand",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
