[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "70427370a61be4434e7e0727549532dfd64f2487"
owners = [
    "Bronya-Rand",
    "vmfunc"
]
maintainers = [
    "Bronya-Rand",
    "vmfunc",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
