[plugin]
repository = "https://github.com/RokasKil/TitleEdit.git"
commit = "43c49558c4aba48b8fb197dbaf86d8f784a215a4"
owners = [
    "RokasKil",
]
project_path = "TitleEdit"
changelog = """
- Extra preset loading logging on failure
"""
