[plugin]
repository = "https://github.com/RokasKil/TitleEdit.git"
commit = "5c03a6530184d7872ea20c2232ff46e0be9597f8"
owners = [
    "RokasKil",
]
project_path = "TitleEdit"
changelog = """
- 7.5 and API15 update
"""
