[plugin]
repository = "https://github.com/RokasKil/TitleEdit.git"
commit = "7bf92cfefbcd608ee1eba3b76d472e7c0fbb1d49"
owners = [
    "RokasKil",
]
project_path = "TitleEdit"
changelog = """
- Fix the game hanging on load (hopefully)
- Improved BGM sheet loading logic
"""
