[plugin]
repository = "https://git.0x0a.de/0x0ade/DP-CustomResolution.git"
commit = "70420406b6f16fc327fab6e141f37c7ec7e48fa6"
owners = ["0x0ade"]
project_path = "CustomResolution2782"
changelog = """
- API15 compat
- Fix compatibility with some Linux environments
- Fix performance regression, mostly noticeable on Linux
"""
