[plugin]
repository = "https://github.com/VioletStardustXIV/XivGearExport.git"
commit = "b11566440534e423f0bdaf9f63f8db0112cd5dfd"
owners = ["VioletStardustXIV"]
project_path = "XivGearExport"
changelog = """
- Added support for Phantom Occultum relic weapons (the ones with selectable stats).
"""
