[plugin]
repository = "https://git.pilzinsel64.de/Pilzinsel64/PlayerTags.git"
commit = "3a1525c68dce370b4146b90f74446efeecf0c7d2"
owners = [
    "Pilzinsel64",
]
project_path = "PlayerTags"
changelog = """- Update for API 15
"""
