[plugin]
repository = "https://github.com/seventity7/Clock.git"
commit = "b7921ff07bd369c2077568671c6b8b67f23e6108"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = """
### **Added:**
- New themes: **Digital**, **Tech**, **Cartoon** **Countdown**
- New option for changing the clock font style
- New **Alarm overlay** with keybind support and better visual/functionality

**Improved:**
- UI cleanup, translation improvements and general stability
- Improved chat time conversion/alarm creation from chat

### Notes
- The `alarm` section was removed from the main window
  - **Alarm management is now focused on `/alarms`**
  - Existing alarm features were reorganized, not removed
- Maintenance reminders are now under **General**
"""
