[plugin]
repository = "https://github.com/seventity7/Clock.git"
commit = "96db6b84eeffc07bb1dd94485208cdcbcdbca19d"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = """
### Changed Chat Timestamp System

The plugin now uses the native timestamp system.
It still does the same things as before:

- shows custom timestamps in chat;
- supports 12-hour and 24-hour time;
- can show or hide `AM/PM`;
- uses the configured time zone offset;
- can apply a custom timestamp color;

### Notes
- `Match Channel Color` option temporarily removed
Please note that if you want to use this feature from this plugin, you might need to disable similar features from other plugins to avoid having any incompatibility in case if there is still any.
"""