[plugin]
repository = "https://codeberg.org/keysmashes/WhosTalking.git"
commit = "3752d7ce5925466e1880835a25e9bd1689718f40" # version 0.8.9.0
owners = ["keysmashes"]
project_path = "WhosTalking"
changelog = """\
Voice indicators should now hide properly when hiding the game UI.
"""
