[plugin]
repository = "https://github.com/Abyeon/HousingCullFix.git"
commit = "d96cbbc9a4f7074ebaf14cc803efda88d3eca6d3"
owners = ["Abyeon"]
maintainers = ["Abyeon, Glorou"]
project_path = "HousingCullFix"
changelog = "Initial release"
