[plugin]
repository = "https://github.com/Abyeon/HousingCullFix.git"
commit = "ec62d29bbc8d49cbe12af4f46aea04948dfece5d"
owners = ["abyeon, glorou"]
maintainers = ["abyeon"]
project_path = "HousingCullFix"
changelog = "Initial release"
