[plugin]
repository = "https://github.com/Noctrepo/NoPolice.git"
commit = "c4d6144bef5d18834ded7f4a71a7dfade0596c85"
owners = ["Noctrepo"]
project_path = "NoPolice"
changelog = "Add chat handler, performance improvements"