[plugin]
repository = "https://github.com/MKhayle/EldenRingDalamud.git"
commit = "96aec686fbb51971faa8a9d299a7af605d6f09d3"
owners = [
	"Roselyyn", 
	"reiichi001",
	"MKhayle"
]
project_path = "EldenRing"
changelog = """
-# API 15 update
"""