[plugin]
repository = "https://github.com/shadowkras/NeatNoter.git"
owners = [ "shadowkras" ]
project_path = "src/NeatNoter"
commit = "f97c3dc73391f997a69195fa6b8061e8f5b9d020"
changelog = """
# NeatNoter 2.7.6 (Test)

## Features

- Updated to patch 7.5.
- Updated to Dalamud sdk 15.
- Added background color and transparency option to the overlay window. Fixed the note edit UI to scale properly with dalamud setting to change UI scaling.

If any bug if found, please report at: https://github.com/shadowkras/NeatNoter/issues/
"""
