[plugin]
repository = "https://github.com/Etheirys/EzMiniCactpot.git"
owners = ["daemitus", "Minmoose", "MidoriKami", "nathanctech"]
project_path = "MiniCactpotSolver"
commit = "6b9dd8dc48bb766d140df9686b37214f535e5fa4"
version = "4.0.1.0"
changelog = """
- Update to API 15
"""