[plugin]
repository = "https://github.com/Cyenia/ffxiv-simplecompare.git"
commit = "710495e964a3fa6c86ae1921d46d6ad4bc985765"
owners = ["Cyenia"]
project_path = "SimpleCompare"
changelog = """
v2.1.2.1
- Update for API 15
"""
