[plugin]
repository = "https://github.com/seventity7/CreateXIV.git"
commit = "773823045166b8699da20b0c88eaba374c3f70b4"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Initial CreateXIV submission"
