[plugin]
repository = "https://github.com/seventity7/CreateXIV.git"
commit = "70dd326b141ff2c799ab7b01be8127e130664548"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Initial CreateXIV submission"
