[plugin]
repository = "https://github.com/Exter-N/Hyperfocus.git"
commit = "8ccc4862c389d4b135a81e8e97ba983bafcec6f4"
owners = ["Exter-N"]
project_path = "Hyperfocus"
changelog = "Update for Dalamud 15"
