[plugin]
repository = "https://github.com/juan-medina/ItsUp.git"
commit = "6541bf222d6e42721344b182cdeaefa94bac8e15"
owners = ["juan-medina"]
project_path = "ItsUp"
changelog = """
- Added support for combo and proc actions.
- Added a Preview mode.
- Smoothed the cooldown swipe.
- Cleaned up settings window.
"""
