[plugin]
repository = "https://github.com/QuackieMackie/QuestJournal.git"
commit = "d22d6e140eb9001af6371f105c5c72ce9fda9162"
owners = ["QuackieMackie"]
project_path = "QuestJournal"
changelog = """
- Bumped version to 1.4.0.1 and updated Dalamud SDK
- Updated quest data
"""
