[plugin]
repository = "https://github.com/Felscream/DragoonMayCry.git"
commit = "52b51fd425b8a88cdce5fc0888350709f2b98576"
owners = ["Felscream"]
project_path = "DragoonMayCry"
changelog = """
- Reduced audio latency
"""
