[plugin]
repository = "https://github.com/Felscream/DragoonMayCry.git"
commit = "2f569a8748e89a1d75e574cb2939543af2e33627"
owners = ["Felscream"]
project_path = "DragoonMayCry"
changelog = """
- API 15 update
"""
