[plugin]
repository = "https://github.com/Felscream/DragoonMayCry.git"
commit = "fe5c249c9dfe947be3e5a9c0e74ec8d728be352c"
owners = ["Felscream"]
project_path = "DragoonMayCry"
changelog = """
- API 15 update
"""
