[plugin]
repository = "https://github.com/OOFGamesss/AethericFlow.git"
commit = "6e63f595276bc4fda89320ef2c0e550568dfd823"
owners = ["OOFGamesss"]
project_path = "AethericFlow"
changelog = "Introducing Aetheric Flow! 1.0 Release!\n\nAdds a teleport link to the nearest aetheryte on every map link in chat.\n\nKey Features:\n- Adds a clickable teleport link after map coordinates in chat.\n- Picks the nearest aetheryte you have attuned in that zone.\n- /aftp teleports to the most recent map link for controller players.\n- Choose which chat channels are scanned.\n- Plenty of customisation options for the links appearance.\n- English, Japanese, German and French are all supported."
