[plugin]
repository = "https://github.com/twelvehouse/ChatAnywhere.git"
commit = "bf26eaabd40857de65084f130519d16653737241"
owners = ["twelvehouse"]
project_path = "."
changelog = "Fix: prevent potential deadlock on plugin unload"
