[plugin]
repository = "https://github.com/twelvehouse/ChatAnywhere.git"
commit = "5bb448b42b618429f552f87a4a04a45393e18099"
owners = ["twelvehouse"]
project_path = "."
changelog = "Fix: show placeholder when DM history is empty"
