[plugin]
repository = "https://github.com/twelvehouse/ChatAnywhere.git"
commit = "2f5829bd476afd6c0836c7398c8002d9a9740872"
owners = ["twelvehouse"]
project_path = "."
changelog = "Fix: prevent accidentally sending /tell to yourself."
