[plugin]
repository = "https://github.com/Bronya-Rand/WukWaymark.git"
commit = "f183dfbf1b99f1e246c24d80dabe1f037c1994b8"
owners = [
	"Bronya-Rand"
]
project_path="WukWaymark"
changelog = """# What's New
- Initial release of WukWaymark to 'testing/live'
- Create and manage custom waymarks
- Configure how waymarks are displayed on the map and minimap
- Set different icons for waymarks (shapes or game icons)
- Add personal notes to waymarks
- Displays in-game locations and world locations by name
- Waymark Groups
- Waymarks per individual character
- Read-Only Shared Waymarks
- Import/Export waymarks
- Fade In/Out effect
- Table/Group View for Waymarks"""
