[plugin]
repository = "https://github.com/Bronya-Rand/WukWaymark.git"
commit = "ac498777e9e37751f78177d28e1dd4b637cd15e2"
owners = [
	"Bronya-Rand"
]
project_path="WukWaymark"
changelog = """# What's New
- Initial release of WukWaymark
- Create and manage custom waymarks
- Configure how waymarks are displayed on the map and minimap
- Set different icons for waymarks (shapes)
- Add personal notes to waymarks
- Displays in-game locations and world locations by name"""
