[plugin]
repository = "https://github.com/wrath16/PvpStats.git"
commit = "2c8c3136225dea26851a2cae8482d011611467fb"
owners = ["wrath16", "rennalol"]
project_path = "PvpStats"
changelog = """
* Patch 7.5 update.
"""