[plugin]
repository = "https://github.com/wrath16/PvpStats.git"
commit = "30ac63fa3785aedd975ef6fdab8da442e149eb4b"
owners = ["wrath16", "rennalol"]
project_path = "PvpStats"
changelog = """
* Enables action analytics tracking for Crystalline Conflict.
* Added disk space saving configuration options.
"""