[plugin]
repository = "https://github.com/wrath16/PvpStats.git"
commit = "3ad7cb2060069dc369f2b80327c30947e8799c7e"
owners = ["wrath16", "rennalol"]
project_path = "PvpStats"
changelog = """
* Added Crystalline Conflict Season 21 filter option.
"""