[plugin]
repository = "https://github.com/NotNite/OfDungeonsDeep.git"
commit = "6be9f0ad84b5a4c94c37c9b7beffa4e52143e53e"
owners = ["NotNite", "MidoriKami"]
maintainers = ["MKhayle"]
project_path = "OfDungeonsDeep"
changelog = """
###
-# - API 15 update
-# - Text can now wrap in ability descriptions (thanks iago-ca)
-# - Updated compendium data, thanks to the compendium contributors :pray: 
"""
