[plugin]
repository = "https://github.com/MidoriKami/VanillaPlus.git"
commit = "07b52b714ae500d33082622fa122d2f13a5be7cf"
owners = [ "MidoriKami",]
maintainers = [ "Haselnussbomber", "Zeffuro",]
project_path = "VanillaPlus"
