[plugin]
repository = "https://github.com/MidoriKami/VanillaPlus.git"
commit = "916bc227638b5bd45726d0f1f8fd5e8de903f8ed"
owners = [ "MidoriKami",]
maintainers = [ "Haselnussbomber", "Zeffuro",]
project_path = "VanillaPlus"
