[plugin]
repository = "https://github.com/MidoriKami/VanillaPlus.git"
commit = "2436581b74541ac325f9a6ccbf160fcb5c1c2be3"
owners = [ "MidoriKami",]
maintainers = [ "Haselnussbomber", "Zeffuro",]
project_path = "VanillaPlus"
