[plugin]
repository = "https://github.com/keifufu/QuestTracker.git"
commit = "58ea84393a18693300b623b6d9078cb7bd16d291"
owners = ["isaiahcat", "keifufu"]
project_path = "."
changelog = """
- Added Levequests
- Improved category and section sorting
"""
