[plugin]
repository = "https://github.com/keifufu/QuestTracker.git"
commit = "c6e2671ec7c17e9a95d3605a749859239dcd0196"
owners = ["isaiahcat", "keifufu"]
project_path = "."
changelog = """
- Added Levequests
- Improved category and section sorting
"""
