[plugin]
repository = "https://github.com/keifufu/QuestTracker.git"
commit = "6ae5bcd9fd031a52fe89aba65e0735c8d630f917"
owners = ["isaiahcat", "keifufu"]
project_path = "."
changelog = """
- Updated for 7.5/API15
"""
