[plugin]
repository = "https://github.com/Ottermandias/GatherBuddy.git"
commit = "1e39592f55e57774f287bfcea87dbd651a5cf2d8"
owners = [
    "Ottermandias",
]
project_path = "GatherBuddy"










