[plugin]
repository = "https://github.com/Ottermandias/GatherBuddy.git"
commit = "f07a5d94ba2b44b075a1783b9cede9723c36b54e"
owners = [
    "Ottermandias",
]
project_path = "GatherBuddy"










