[plugin]
repository = "https://github.com/Ottermandias/GatherBuddy.git"
commit = "c9b4a99dd32686fe5a9ba64297fe3143b162b5e9"
owners = [
    "Ottermandias",
]
project_path = "GatherBuddy"










