[plugin]
repository = "https://github.com/Blackcatz1911/CurrencySpender.git"
owners = ["Blackcatz1911"]
project_path = "CurrencySpender"
commit = "2b9fb128fa85c814e7d69844569314fc3c98bfaa"
changelog = """
## 1.2.7
### Added
- New Currencies: Oizys Credits & Auxesia Credits.
- Highlighting for NPCs and items/menus thanks to electr0sheep.
- Option to automatically add/remove upgrade items to \\\"Items of Interest\\\".
### Fixed
- Select Bait Ball was missing.
"""
version = "1.2.7"
