[plugin]
repository = "https://github.com/KangasZ/EurekaHelper.git"
commit = "c0c169f8654a1ab45d443d17f90ca40d54557b4c"
owners = ["snorux", "KangasZ"]
project_path = "EurekaHelper"
changelog = """
- API 15 / 7.5 Update
"""
