[plugin]
repository = "https://github.com/silasary/apxiv.git"
commit = "017d051f838c55d93d508b0e927151af64b7a0b4"
owners = ["silasary"]
project_path = "ArchipelagoXIV"
changelog = "More bugfixes.  Better support for non-english clients (Still not perfect, but progress)."
