[plugin]
repository = "https://github.com/silasary/apxiv.git"
commit = "e1f96e902d28a6232ca754343ce6dc97a999f0a7"
owners = ["silasary"]
project_path = "ArchipelagoXIV"
changelog = "Patch 7.5 support."
