[plugin]
repository = "https://github.com/Tischel/ActionTimeline.git"
commit = "6392e3ebebbb3ba9f3aab51bca792ff64f2e10e1"
owners = ["Tischel"]
project_path = "ActionTimeline"
changelog = "- Added support for Patch 7.5 and Dalamud API 15."