[plugin]
repository = "https://github.com/karashiiro/SoundSetter.git"
commit = "675dedb600fe235f370a3b73f2f7c9b4f3842183"
owners = ["karashiiro"]
changelog = """\
- Fixed incorrect config values in plugin UI before making changes.
"""
