[plugin]
repository = "https://github.com/ZhyraPlugins/PartyPlanner.git"
commit = "6b15d63bc0dba298958465460ca3dbf36b775bff"
owners = ["edg-l"]
project_path = "PartyPlanner"
changelog = """
- Updated for Dalamud API 15
"""
