[plugin]
repository = "https://github.com/Zeffuro/AetherBags.git"
commit = "8dfbdcf2ddcfabd91d7b24fb0ff44ade6ffc8929"
owners = ["Zeffuro"]
maintainers = ["Seeker1437"]
project_path = "AetherBags"
