[plugin]
repository = "https://github.com/Zeffuro/AetherBags.git"
commit = "3ad0400c8b09c3b2839a7cef6a20341dd6fc4a13"
owners = ["Zeffuro"]
maintainers = ["Seeker1437"]
project_path = "AetherBags"
