[plugin]
repository = "https://github.com/MKhayle/BetterTargetingSystem.git"
commit = "b3b6f2942bb89a6ecca869d3d4b3a972f5bcb584"
owners = ["Lynesth", "MKhayle"]
project_path = "BetterTargetingSystem"
changelog = """
-# Fixed the target filter"""
