[plugin]
repository = "https://github.com/MKhayle/BetterTargetingSystem.git"
commit = "6489a590c46f6edbc5e50333142c4b0b0c7814b3"
owners = ["Lynesth", "MKhayle"]
project_path = "BetterTargetingSystem"
changelog = """
-# API 15 update"""
