[plugin]
repository = "https://github.com/MKhayle/BetterTargetingSystem.git"
commit = "0d7dd961dc7d4c75f31a7ecfab52231dfd5c7e22"
owners = ["Lynesth", "MKhayle"]
project_path = "BetterTargetingSystem"
changelog = """
-# API 15 update"""
