[plugin]
repository = "https://github.com/fj233/FriendNote.git"
commit = "94a3b37ed292d381ec9374985b17b2fc435d16b1"
owners = ["fj233"]
project_path = "FriendNote"
changelog = "Add personal notes to friends from the friend list context menu. Right-click a friend's name to set a note, which will then be shown in the friend list."
