[plugin]
repository = "https://git.0x0a.de/0x0ade/DP-CustomEqualizer.git"
commit = "8472724cddc525006c60be0594e25e2f30989808"
owners = ["0x0ade"]
project_path = "CustomEqualizer2782"
changelog = """
- Initial stable release
"""
