[plugin]
repository = 'https://git.anna.lgbt/XIVChat/XIVChat.git'
commit = 'ee9759e68ec6144f334d90277a77b88480346b42'
owners = [ 'anna-is-cute' ]
project_path = 'XIVChatPlugin'
changelog = """\
- API 15
"""
