[plugin]
repository = 'https://git.anna.lgbt/XIVChat/XIVChat.git'
commit = 'f8a7cd345135799d32be7b1795f296f97fadf8c7'
owners = [ 'anna-is-cute' ]
project_path = 'XIVChatPlugin'
changelog = """\
- API 15
"""
