[plugin]
repository = "https://github.com/mashirochan/FFXIV-WaveWrangler.git"
commit = "73c4fe25b447f7fd0d36a2b611f7e87acc7a1588"
owners = ["mashirochan"]
project_path = "WaveWrangler"
changelog = "Update to API 15"
