[plugin]
repository = "https://github.com/Kurochi51/PetScale.git"
commit = "646dbb284be77e2f2763573e83a9f43414adc285"
owners = ["Kurochi51"]
project_path = "PetScale"
changelog = """
- Beastmaster support
This is being released early for... reasons.
"""
