[plugin]
repository = "https://github.com/RulHolos/Bartender.git"
commit = "1c02032c3581c0ef33770594bbfe7ee1c52010c4"
owners = ["RulHolos"]
project_path = "Bartender"
changelog = """
- Pet condition fixed
"""
