[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "0fd67356013891c5719e2d354bfd0b7f53d02b0f"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Rework Complete - Letting this simmer in testing while I make a few voiceline packs."