[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "eaabe20a14f80d15a608b10f698df7f48060254f"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Some Edits - Added More Cutscene Lines and announcers!"
