[plugin]
repository = "https://github.com/spide-r/PvPAnnouncer.git"
commit = "84c2b9004711c2fe9a21463397ad793db9376881"
owners = ["spide-r"]
project_path = "PvPAnnouncer"
changelog = "Some Edits - Added More Cutscene Lines to data"
