[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "bd0caa972fa100e3fcdaf5bc805f3d9fd2164f2e"
owners = ["Glyceri",]
	changelog = """
[2.10.0.1]
Fixes a longstanding issue where the party list members would not allign properly.
"""

