[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "71922642427b8d374d5f16adc82bfcb7385b0022"
owners = ["Glyceri",]
changelog = """
[Pet Nicknames 3.0.0.0]

Helloooo helloooooo!
This is a majour rewrite of Pet Nicknames that has been ongoing for the last year.
Sorry this took so long.

- Added support for Beast Master naming.
- Added an ephemeral chat replace (on by default) where chat messages will update retroactively and disappear when the plugin turns off.
- Massive stability improvements, naming is now much more consistant, and lots of UI elements will update themselves.
- Slight UI rework.
- Added multiple languages (If your language is missing, feel free to message me). [French (Matias49), Japanese (Epinephren), German (Epinephren), Chinese (MapleRecall), Dutch (Glyceri), English (Glyceri)] 
- It *should* now work on the non-global clients too.
- Added support for LOVM (I think)
- Added (proper) support for Island Pets.

Please notify me of any remaining issues. 
It's hard to find them all on my own.
"""

