[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "822673fdcc99310aa3a092291a788524098f52db"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "- Update for 7.5 hotfix compatibility"
