[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "1861dca6e27eaafabd42f9a0e29b8b2f5086dccd"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "- Update for 7.5 / API15"
