[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "357f96a55dfbe82bb5f115591ebbc9b795c58342"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "- Update for 7.5 / API15"
