[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "2fec161f36e8ee29397191378c10dccf4a9c81d8"
owners = ["seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.3.0
- Additional & improved Tooltips and Filters
"""