[plugin]
repository = "https://github.com/Kurochi51/PetScale.git"
commit = "1b61f09eb2847f138c1b4cdffd842e5011c50f62"
owners = ["Kurochi51"]
project_path = "PetScale"
changelog = """
- Fixed some self-inflicted exceptions.
- Separated the saved entries view for beastmaster and summoner
Warning: 
- There's a very real chance that I ommited something, or broke some of the existing scaling, so this is a true testing release.
  
  Data should be unaffected by this change, but I can't make any guarantees.
"""
