[plugin]
repository = "https://github.com/Kurochi51/PetScale.git"
commit = "cc6e9e4ca782059263f3d7e8266d4105de60cb5b"
owners = ["Kurochi51"]
project_path = "PetScale"
changelog = """
- Quarterly API Bump
"""
