[plugin]
repository = "https://github.com/LatencyBryer/QuickSymbols.git"
commit = "dd06efc082fe9d2b195a86d23a43b2aee7ee6678"
owners = ["LatencyBryer"]
maintainers = ["LatencyBryer"]
project_path = "."
changelog = """
### What's New?
- Fixed "♥" button alignment/centering
- The "♥" button now appears in more native windows:
  - User Macros
  - Strategy Board
Note: The symbol list can be opened through keybind in any native window, the button is just to make it easier.
"""
