[plugin]
repository = "https://github.com/LatencyBryer/QuickSymbols.git"
commit = "2566d1a593b05dcc4bb454b1997ffd8aa5ffd76f"
owners = ["LatencyBryer"]
maintainers = ["LatencyBryer"]
project_path = "."
changelog = """
- Added IPC support/documentation
"""
