[plugin]
repository = "https://github.com/Kouzukii/ffxiv-deathrecap.git"
commit = "658ec3a19614f225e354b207ebba87aaf64943c7"
owners = ["Kouzukii"]
project_path = ""
changelog = """
- Update to FFXIV 7.5 and Dalamud 15
"""
