[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "2af83cb4b8d40a3f1c97c609caad1ee593289a78"
changelog = """
General: Updated for 7.5
    System: Internal changes to facilitate faster updates in the future"""
