[plugin]
repository = "https://github.com/smadam813/EzWondrousTails.git"
owners = ["daemitus", "MidoriKami", "nathanctech", "smadam813"]
project_path = "WondrousTailsSolver"
commit = "ff79c7642b0fc9b90c04461cb7d844720b4f95ae"
version = "3.2.2.7"
