[plugin]
repository = "https://github.com/ryankhart/RestoreCameraPivotWhileAutorunning.git"
commit = "926243e6dfdc85d8cc479327ca66f635677d11bf"
owners = ["ryankhart"]
changelog = "Initial testing release."
