[plugin]
repository = "https://github.com/ryankhart/RestoreCameraPivotWhileAutorunning.git"
commit = "8a533c2f896c4549b47555ce19100e14c2b1e6bc"
owners = ["ryankhart"]
changelog = "Initial testing release."
