[plugin]
repository = "https://codeberg.org/Linneris/dalamud-snooper.git"
commit = "dbd107ebcdb0ba9b67342fbe1788b07751073062"
owners = ["Maia-Everett"]
project_path = "Snooper"
changelog = """
* Hopefully fixed "System.Collections.Generic.KeyNotFoundException: The given key 'TellOutgoing' was not present in the dictionary.".
* Slightly enlarged the config window to fit all controls.
"""
