[plugin]
repository = "https://github.com/Aida-Enna/TeamcraftListMaker.git"
commit = "43f24ba7359d6e9855a8e36eb4853491a3d5bd95"
owners = ["Aida-Enna"]
project_path = ""
changelog = "- Have it split lists if it exceeds 100 items on export"
