[plugin]
repository = "https://github.com/teechep/FATEhelper.git"
commit = "91d4e84d844d75cb1be676ba7cdd17cc121d8750"
owners = ["teechep"]
project_path = "FATEhelper"
changelog = "API v15, added option for forlorn spawn sound effect"
