[plugin]
repository = "https://github.com/teechep/FATEhelper.git"
commit = "d9c40bd646698e118db6d867cda9fb40a52ede6b"
owners = ["teechep"]
project_path = "FATEhelper"
changelog = "added distance view and sort option, huge thanks to jade-doggerel on github for this <3"
