[plugin]
repository = "https://github.com/Bronya-Rand/ThingsToDoInEorzea.git"
commit = "e173d924a739dbb1692ecd5698c6db6b606d687f"
owners = [
    "Bronya-Rand"
]
maintainers = [
    "Bronya-Rand"
]
project_path = "ThingsToDoInEorzea"
