[plugin]
repository = "https://github.com/Jrogo7/VenueManager.git"
commit = "4f11f37559faff9928af6b3ec837af1dc89afad0"
owners = ["Jrogo7"]
project_path = "VenueManager"
changelog = """

- Dalamud 15 

"""