[plugin]
repository = "https://github.com/Jrogo7/VenueManager.git"
commit = "38645869ebe52d9daaf9e4949749aa88b85200ab"
owners = ["Jrogo7"]
project_path = "VenueManager"
changelog = """

- Dalamud 15 

"""