[plugin]
repository = "https://github.com/keifufu/JobTitles.git"
commit = "be1a0843bd27c279279f6d8d0d3997df544ddb5f"
owners = ["keifufu"]
project_path = "."
changelog = """
- Support for Beastmaster
"""
