[plugin]
repository = "https://github.com/wolfcomp/MonsterDex.git"
owners = [ "wolfcomp" ]
project_path = "DeepDungeonDex"
commit = "7e0bc25c8a67b08f6d243e7a4c2a770bcadd96da"
changelog = "## 2.15.0 (2026-04-30)\n\n\n### Features\n\n* API 15 update (01562f8)\n* configurable icon draw tints (06a36bd)"
version = "2.15.0"
