[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "708d6256a36b30c07e5b51e154bef807028f55bc"
owners = [
    "Bronya-Rand"
]
maintainers = [
    "Bronya-Rand",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
