[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "9d4d55ab5e2240e5b04ebbdca0065aff71ee4489"
owners = [
    "Bronya-Rand",
    "vmfunc"
]
maintainers = [
    "Bronya-Rand",
    "vmfunc",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
