[plugin]
repository = "https://github.com/Bronya-Rand/Dalamud.RichPresence.git"
commit = "bf70912fab64c5b1f4fb225d18b5cdb8b0df8188"
owners = [
    "Bronya-Rand"
]
maintainers = [
    "Bronya-Rand",
    "reiichi001",
    "goaaats"
]
project_path = "Dalamud.RichPresence"
