[plugin]
repository = "https://github.com/Aida-Enna/RandomClassSelector.git"
commit = "93ad7bdfd3e744d9111dc485b21eb9d89fc7a929"
owners = ["Aida-Enna"]
project_path = ""
changelog = "- Updated for 7.5"
