[plugin]
repository = "https://github.com/Aida-Enna/RandomClassSelector.git"
commit = "35039f126e605c1a0fa6f79eda2271ff94cddc1b"
owners = ["Aida-Enna"]
project_path = ""
changelog = "- Updated for 7.5"
