[plugin]
repository = "https://github.com/j0giwa/ComfyLoot.git"
commit = "9ab2ecbcca20726e4ee4858cf51febb2740895bd"
owners = ["j0giwa"]
project_path = "."
changelog = """
v1.0.5.0
- Added Unignore-gate to IPC

v1.0.4.0
- Fixed some issues with the main UI
- Added IPC to interact with other plugins

v1.0.3.0
- Updated to work with game version 7.5
- API 15
- Fixed issue where certain zones are shown as "???" on the filter tab

v1.0.1.0
- API14
- Traded loot is now propperly recognized

v1.0.0.1
- Fixed scrolling behaviour in the UI

v1.0.0.0
- Prettified UI
- Added sorting capability
- Added ability to temporarily hide items

v0.9.8.5
- Added ignore lists
- Fixed unload issue

v0.9.6.5
- Internal Refactor
- Introduced Threadsafety
- Resolved issue where switching to an alt tracked your alts inventory as drops

v0.9.5.5: Added Server Info Entry.
- Added toggleable ServerInfo Bar (OFF by default)
- addressed internal issues
"""
