[plugin]
repository = "https://github.com/j0giwa/ComfyLoot.git"
commit = "ddc3c9a3da27ee6ee1e49bf0ef91c7c1f0caf919"
owners = ["j0giwa"]
project_path = "."
changelog = """
v1.0.3
- Updated to work with game version 7.5
- API 15
- Fixed issue where certain zones are shown as "???" on the filter tab
"""
