[plugin]
repository = "https://github.com/Hiroa/LazyGatherer.git"
commit = "0bb8ec9a47dc4521411c705221cdeda361015d75"
owners = ["Hiroa"]
project_path = "LazyGatherer"
changelog = """
Version 1.4.5: 
 - Rework estimated yield display
 - Take boon chance into consideration when calculating min/max
"""