[plugin]
repository = "https://github.com/Hiroa/LazyGatherer.git"
commit = "69e50a2b8804464a6473e1d6236fb6655fd7a4b0"
owners = ["Hiroa"]
project_path = "LazyGatherer"
changelog = """
Version 1.4.4: 
 - Improve stability
"""