[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "ea8cacd4823653bb8b02e5db5664a836dc0f0e4a"
version = "1.8.1.32"
owners = ["CMDRNuffin"]
changelog = '''
Update for 7.5'''
