[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "f04323fa9383d429130aab6abdf7ad5fcea5fbb9"
version = "1.8.1.31"
owners = ["CMDRNuffin"]
changelog = """
Add Hardy-Daytona to the list of fast ground mounts
"""
