[plugin]
repository = "https://github.com/sourpuh/ffxiv_borderless_fix.git"
commit = "b4e584a98df90136d9c1c55076d6f9b0c5011048"
owners = [
    "sourpuh",
]
project_path = "borderless-fix"
changelog = "Update for API 15"
