[plugin]
repository = "https://github.com/sleeds2/jobroulette.git"
commit = "b94579af3c67f7bb3a848803b23ecec97fd0aac3"
owners = ["sleeds2"]
maintainers = ["mchudoba"]
project_path = "JobRoulettePlugin"
changelog = """\
**Update**: Added class support.
"""
