[plugin]
repository = "https://github.com/meoiswa/autobgm.git"
commit = "a8a2aea65cf311d6f992e2775191c5dccb2e7f22"
owners = ["meoiswa"]
project_path = "AutoBGM"
changelog = """
Version 1.5.1.0:
 - Updated to API15
"""
