[plugin]
repository = "https://github.com/Lovasz-Akos/DispellerPlugin.git"
commit = "a0506935fe08782230b34ef279aa1589f0caf89a"
owners = ["pupwife"]
maintainers = ["naara"]
changelog = """
- Updated to API 15
- Fixed model detection skipping too many things to list
- Fixed Armoire detection
- Fixed HQ and NQ items not being compared
- Added a config window
- Added color variance filtering
- Added name copy button for quick serach
"""