[plugin]
repository = "https://github.com/seventity7/ESTClock.git"
commit = "a0e97c746757699f1658bfdf6b3b12046515a8fe"
owners = ["seventity7"]
maintainers = ["seventity7"]
project_path = "."
changelog = "Initial official submission/update 1.0.4"
