[plugin]
repository = "https://github.com/PunishedPineapple/ItemUse.git"
commit = "2e7dfc5f7eb122aea5b8705706d4bd8c5000f42d"
owners = [
    "PunishedPineapple",
]
project_path = "ItemUse"
changelog = '''
- Updated for Dalamud API 15 and the new UI themes added with patch 7.5.
'''