[plugin]
repository = "https://github.com/Critical-Impact/Tippy.git"
owners = [ "kalilistic", "Critical-Impact",]
project_path = "src/Tippy"
commit = "645ca70da43dd705f7cf571ebe0823fe62e215cb"
version = "1.15.0.0"
changelog = "### Changed\n- API15 update"
