[plugin]
repository = "https://github.com/Shiori-Zephyr/Uwu-Chat.git"
commit = "72c384ee0807e13960ff6c6f5ccfe9d566b24e0e"
owners = ["Shiori-Zephyr"]
project_path = "UwuChat"
changelog = "Initial release"
