[plugin]
repository = "https://github.com/Shiori-Zephyr/Uwu-Chat.git"
commit = "b4ad99101be192abb3a89daa97d1cad29736d6db"
owners = ["Shiori-Zephyr"]
project_path = "UwuChat"
changelog = "Initial release"
