[plugin]
repository = "https://github.com/Skyde789/GlamSwapCommandPlugin.git"
commit = "747a0d2e6b5c9d813a8c9aa6f378ff71d896c29b"
owners = ["Skyde789"]
project_path = "GlamSwapCommand"
changelog = "API 14 -> 15"