[plugin]
repository = "https://github.com/karashiiro/TextToTalk.git"
commit = "40f0dd1ef61786eef55160acb32af2e470014ce3"
project_path = "src/TextToTalk"
owners = ["karashiiro"]
changelog = """\
- **WebSocket**: Adds raw message payloads for external TTS engines to consume (thanks `@barrcodes`!).
"""
