[plugin]
repository = "https://github.com/karashiiro/TextToTalk.git"
commit = "b026e5d34b0208bd5c066af0ad9912184914279e"
project_path = "src/TextToTalk"
owners = ["karashiiro"]
changelog = """\
- **Azure**: Fixed crash when disabling/updating the plugin during speech playback.
"""
