[plugin]
repository = "https://github.com/sleeds2/glamourroulette.git"
commit = "6396eabba108c84e4ef4c2801dbfe02ea941ea25"
owners = ["sleeds2"]
maintainers = ["mchudoba"]
changelog = """\
**New Plugin**: Glamour Roulette is a plugin for Final Fantasy XIV that randomly selects one of your saved Glamour Plates and swaps to it.
- Allows the user to select eligible gearsets to be randomized.
- Don't know what to wear tonight? Glamour Roulette has you covered!
"""
