[plugin]
repository = "https://github.com/in1tiate/Wikilinx-Dalamud.git"
commit = "d1a357f0c3bfbaad070b72de4f366a8b5b11e80f"
owners = ["in1tiate"]
project_path = "WikilinxPlugin"
changelog = "Added option to always open wiki with English item name (by pixelify32, thank you!) and bumped Eorzea DB IDs to 7.55"


