[plugin]
repository = "https://github.com/Tischel/NOTED.git"
commit = "5900af34c3031e3681196d1dcb9ba8fcd249f91d"
owners = ["Tischel"]
project_path = "NOTED"
changelog = "- Added support for Patch 7.5 and Dalamud API 15."