[plugin]
repository = "https://github.com/mashirochan/FFXIV-BatteryBuddy.git"
commit = "6d5f2cbbdfe3a82703a208ce119834d17e0ae722"
owners = ["mashirochan"]
project_path = "RazerReader"
changelog = "Fix low battery notification timer"
