[plugin]
repository = 'https://github.com/zeroeightysix/remote-party-finder.git'
commit = 'aaef193db362356bbdfa585b7ef1d1efa8f2f5ee'
owners = [ 'zeroeightysix' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for 7.55'
