[plugin]
repository = "https://github.com/meoiswa/MagitekStratagem.git"
commit = "d6f83d2596665b63bffe64b96c9587826d1f3a8a"
owners = ["meoiswa"]
project_path = "MagitekStratagem"
changelog = """
Version 1.4.0.0:
 - Feat: Configurable Opentrack port


Known Issues:
 - Windowed mode is currently unsupported.
"""
