[plugin]
repository = "https://github.com/meoiswa/MagitekStratagem.git"
commit = "06e4ae34deed526b419afd5da62336c20f3b5094"
owners = ["meoiswa"]
project_path = "MagitekStratagem"
changelog = """
Version 1.3.1.1:
 - New Icon by SnoodleWolfieB
 - Updated to API15


Known Issues:
 - Windowed mode is currently unsupported.
"""
