[plugin]
repository = "https://github.com/danielbrenom/MonsterLootHunter.git"
commit = "1e603afc0c60d12c401eb6b7b360623dee766ebc"
owners = [
    "danielbrenom",
]
project_path = "MonsterLootHunter"
changelog = """- Update for API 15
 """
