[plugin]
repository = "https://github.com/lokinmodar/Echoglossian.git"
commit = "720e655e213d0bb105154272a04c36098d75bb07"
owners = ["lokinmodar"]
changelog = "v4.2600.1105.x \n fixes:\n - stabilized setup, engine selection, and first-use activation\n - improved action and main menu translation reuse between game versions\n - fixed translator cache concurrency and several native UI read-only rewrite regressions"
