[plugin]
repository = "https://github.com/cassandra308/WhereAmIAgain.git"
owners = ["cassandra308", "reiichi001", "MidoriKami", "nathanctech"]
project_path = "WhereAmIAgain"
commit = "4c84583942de617feeaf2e05ca48184afa3a89b5"
version = "2.1.1.6"
