[plugin]
repository = 'https://github.com/MKhayle/Namingway.git'
commit = 'dd8c4303ca943accc3b42e6b430f99a303223398'
owners = [ 'anna-is-cute', 'MKhayle' ]
changelog = """-# Tentative bugfix for the Status Replacement crash some users were facing under specific conditions."""
