[plugin]
repository = "https://github.com/wrath16/MapPartyAssist.git"
commit = "620731282ebf17029afa2cf37733816dafcacb75"
owners = ["wrath16"]
project_path = "MapPartyAssist"
changelog = """
* Patch 7.5 update.
"""