[plugin]
repository = "https://github.com/Abyeon/CustomLoadingScreens.git"
commit = "86fd547e3c793baf4301c021426348f180589a28"
owners = ["Abyeon"]
project_path = "CustomLoadingScreens"
changelog = "Initial Release"
