[plugin]
repository = "https://github.com/dechamps-chen/DotPosition.git"
commit = "e3cf0173bb8fac71616999c3b404748d74854f94"
owners = ["dechamps-chen"]
project_path = "DotPosition"
version = "1.0.0.4"
