[plugin]
repository = "https://github.com/chirpxiv/SelfCare.git"
commit = "3a157368dea6162c318789e867a4c97a270c10dd"
owners = ["chirpxiv", "MKhayle"]
project_path = "SelfCare"
changelog = """
-# API 15 update
-# No longer steals focus from other plugin windows when triggered (thanks Valiice!)
"""