[plugin]
repository = "https://github.com/sourpuh/ffxiv_gaolbreak.git"
commit = "871d70fc6ede76b6b20994db2f86ca348d0d8e73"
owners = ["sourpuh"]
project_path = "Gaolbreak"
changelog = """\
**Initial Main Repo Testing Release**
- Layer game windows with plugin windows
- Allow 3D overlay plugins to draw under the game's UI
- Prevent ReShade or other graphics effects from affecting the UI
"""
