[plugin]
repository = "https://github.com/fieldcontentenjoyer-xiv/ResStackCounter.git"
commit = "c0106e763a837842de4d812e002676dac2178b54"
owners = [ "fieldcontentenjoyer-xiv" ]
project_path = "ResStackCounter"
