[plugin]
repository = "https://github.com/fieldcontentenjoyer-xiv/ResStackCounter.git"
commit = "0014190dc0111daaeb4b09680f11184814c42142"
owners = [ "fieldcontentenjoyer-xiv" ]
project_path = "ResStackCounter"
