[plugin]
repository = "https://github.com/fieldcontentenjoyer-xiv/ResStackCounter.git"
commit = "f60127935f4f190f2bdac205421abfd637d9b6fa"
owners = [ "fieldcontentenjoyer-xiv" ]
project_path = "ResStackCounter"
