[plugin]
repository = "https://github.com/iri-impulse/PhotoboothPlugin.git"
commit = "5042d22592e6cb498101cea9a31b8cf6120e7eb2"
owners = ["iri-impulse"]
project_path = "Photobooth"
changelog = """\
1.0.1:
- Update for patch 7.5
- Fix diagram title flicker when right-dragging
"""
