[plugin]
repository = "https://github.com/Kouzukii/ffxiv-whichpatchwasthat.git"
commit = "5578bad66709f92811fe43b5c533144593a45d70"
owners = [
    "Kouzukii",
]
project_path = "WhichPatchWasThat"
changelog = """
- Update to FFXIV 7.5 and Dalamud 15
- Add patch display to facewear
"""