[plugin]
repository = "https://github.com/devckuw/BetterFriendList.git"
commit = "c35c678c10df41206fe63effd646486b66252b09"
owners = ["devckuw"]
project_path = "BetterFriendList"
changelog = """
add:
    refresh button in native friend list
    collapse button on social (player search / friend list / party members)
    option to prevent friendlist to refresh on open
    option to show notes in native friend list
    option to use color in native friend list
    option to keep same keybind for both native and plugin friend list
    restriction when requesting data (gpose, disconnected, offline, cutscene, afk, camera mode)
fix:
    fix refresh when used on specific player
    fix lodestone page with name with special chars
    fix icons for crossworld party leader and memeber
    fix condions for pf button
    fix request data not being called when opening HousingMate addon
"""
