[plugin]
repository = "https://github.com/devckuw/BetterFriendList.git"
commit = "f13c7e25acc03ddf9fec59bb62f2fa2223476834"
owners = ["devckuw"]
project_path = "BetterFriendList"
changelog = """
add:
    refresh button in native friend list
    collapse button on social (player search / friend list / party members)
    option to prevent friendlist to refresh on open
    option to show notes in native friend list
    option to use color in native friend list
    option to keep same keybind for both native and plugin friend list
fix:
    fix refresh when used on specific player 
"""
