[plugin]
repository = "https://github.com/reiichi001/Dalamud.DiscordBridge.git"
commit = "7bb325a5cca5d41664ffd34b0a27eea6b3a28e4f"
owners = [
    "reiichi001",
	"goaaats",
]
maintainers = [
    "reiichi001",
	"goaaats",
]
project_path = "Dalamud.DiscordBridge"
changelog = """
Switches to caching player name and world from PlayerState. This has been moved from Framework updates to only login and territory change.

This plugin is looking for a new owner/maintainer. Please reach out to Franz if you want to adopt it.
"""