[plugin]
repository = "https://github.com/reiichi001/Dalamud.DiscordBridge.git"
commit = "6a64306a31336393ba2b037aabf9ec7bd1ab4ff8"
owners = [
    "reiichi001",
	"goaaats",
]
maintainers = [
    "reiichi001",
	"goaaats",
]
project_path = "Dalamud.DiscordBridge"
changelog = """
Fix local player world detection.

This plugin is looking for a new owner/maintainer. Please reach out to Franz if you want to adopt it.
"""