[plugin]
repository = "https://github.com/mikelosx/Shrinkage.git"
commit = "5a3db953435e0c927df72ab28e68e38eb301f7ab"
owners = ["mikelosx"]
project_path = "Shrinkage"
changelog = "initial, characters scale size based on hp and barrier"
