[plugin]
repository = "https://github.com/Frogworks-Interactive/OOF.git"
commit = "86ed0f5a615c80ab59641b25746cd4d11294533b"
owners = [
    "Frogworks Interactive",
    "codelastnight"
]
project_path = "OofPlugin"
changelog = """
- update for api 15
"""