[plugin]
repository = "https://github.com/s5bug/CongaHelper.git"
commit = "23be53415afb22cb94868dbc264616ccb6a7644e"
owners = ["s5bug"]
project_path = "CongaHelper"
changelog = '''
- Adds a command /conga as well as a button to the Party List GUI to arrange the party list in the same order as characters appear in the world. useful for TOP conga etc.'''
