[plugin]
repository = "https://github.com/apetih/LogogramHelper.git"
commit = "022035a066ca11539f6fdfde1f5d6b9e88bd5962"
owners = ["apetih"]
project_path = "LogogramHelper"
changelog = """
- API 15
"""
