[plugin]
repository = "https://github.com/goaaats/Dalamud.FindAnything.git"
commit = "45a3a614db02007d02a9809f52ea5f9a2f480e27"
owners = ["goaaats"]
maintainers = ["nebel"]
project_path = "Dalamud.FindAnything"
