[plugin]
repository = "https://github.com/goaaats/Dalamud.FindAnything.git"
commit = "8e885436c2fbda975a18814f2a5c9eb41f3a09cf"
owners = ["goaaats"]
maintainers = ["nebel"]
project_path = "Dalamud.FindAnything"
