[plugin]
repository = "https://github.com/ssalazar217/CharacterProfileSwitch.git"
commit = "996048f7c02a63d122d928f10faa546c1320491e"
owners = ["ssalazar217"]
project_path = ""
changelog = """
v0.1.0.0:
- Initial release.
- Automatically switch plugin set when you log in with each character.
- Group characters (Name@World) and assign a list of plugins per profile.
- Use /cps to open settings.
"""
