[plugin]
repository = "https://github.com/Critical-Impact/AllaganItemSearch.git"
commit = "e25d3a8b72372becd1d5ff678db03720ac0f129d"
owners = [ "Critical-Impact",]
project_path = "AllaganItemSearch"
version = "1.3.0.2"
changelog = "### Added\n- Updated data for 7.55"
