  [plugin]
  repository = "https://github.com/CallumCarmicheal/XIVControllerToggle.git"
  commit = "7953a6260352263fe71ca10911e11f29152d4592"
  owners = ["CallumCarmicheal", "Aida-Enna"]
  project_path = ""
  changelog = """
  # The Great Controller HUD Switcher 1.2.5
  - Add changelog window
  - Update to Dalamud API 15
  """
