  [plugin]
  repository = "https://github.com/CallumCarmicheal/XIVControllerToggle.git"
  commit = "f1df00daa3a32f1c44485111c69d228db946756f"
  owners = ["CallumCarmicheal", "Aida-Enna"]
  project_path = ""
  changelog = """
  A special thanks to these contributors (github usernames):
  - @Aida-Enna: Updating the plugin to be Dawntrial compatible.
  - @grecaun, @imvaskel: Updating the plugin dalamud API and to FFXIV patch.
  - @TheThirdDoor: Quality of life improvements and WASD binding.

  # The Great Controller HUD Switcher 1.2.4
  - Change WASD keys to use ffxiv keys bound for character movement, adds support for other keyboard layouts like AZERTY or 
    custom movement keybinds, thanks @TheThirdDoor
  - Ignore keyboard inputs when a chat/text field is active. thanks @TheThirdDoor

  # The Great Controller HUD Switcher 1.2.3
  - Updated to latest Dalamud API and FFXIV patch version, thanks @imvaskel

  # The Great Controller HUD Switcher 1.2.2
  - Updated to latest API version and FFXIV Patch, thanks @grecaun
  
  # The Great Controller HUD Switcher 1.2.1
  - Fix issue with several configuration variables not saving.

  # The Great Controller HUD Switcher 1.2
  - Added UI Scaling option to change scaling when swapping between KBM / PAD.

  # The Great Controller HUD Switcher 1.1
  - Updated to DT 7.2
  - Added collection enabling / disabling upon switching

  # The Great Controller HUD Switcher 1.0.1.3
  - Updated to DT 7.1
  - Added hide chat on switch when changing hud layout

  # The Great Controller HUD Switcher 1.0.1.2
  - Fixed issue with configuration UI not changing HUD selection

  # The Great Controller HUD Switcher 1.0.1.1
  - Updated to Dawntrial (7.X) by Aida-Enna

  # The Great Controller HUD Switcher 1.0.1.0
  - Attempted to fix display scaling on larger DPI monitors
  - Fixed issue where main plugin command was registered twice
  
  # The Great Controller HUD Switcher 1.0.0.0
  - Made it work(tm)"""
